name: country_app
description: Project to show country and cities.

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  firebase_core: 2.4.0
  cloud_firestore: 4.2.0
  firebase_core_platform_interface: 4.5.2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
