// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ASvInrITSV6-x76ky90c6aJd-QAkwvE',
    appId: '1:597907912901:web:788dbe717918c4c15d58ac',
    messagingSenderId: '597907912901',
    projectId: 'country-bf992',
    authDomain: 'country-bf992.firebaseapp.com',
    storageBucket: 'country-bf992.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_X8e_KgZMloiOCI9KXtycel17LQiRrk',
    appId: '1:597907912901:android:876ba87349b01eb85d58ac',
    messagingSenderId: '597907912901',
    projectId: 'country-bf992',
    storageBucket: 'country-bf992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBP_vri-9ZIWoTnAXskTzYH4YgGGPrSc',
    appId: '1:597907912901:ios:413f8e84b6b4a01f5d58ac',
    messagingSenderId: '597907912901',
    projectId: 'country-bf992',
    storageBucket: 'country-bf992.appspot.com',
    iosClientId: '597907912901-e5t1mf29d90nedi9vknfog0g0t8iv0vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.country_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBP_vri-9ZIWoTnAXskTzYH4YgGGPrSc',
    appId: '1:597907912901:ios:413f8e84b6b4a01f5d58ac',
    messagingSenderId: '597907912901',
    projectId: 'country-bf992',
    storageBucket: 'country-bf992.appspot.com',
    iosClientId: '597907912901-e5t1mf29d90nedi9vknfog0g0t8iv0vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.country_app',
  );
}
